In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/cleaned/SampleSuperstore_Cleaned_Final.csv")

In [3]:
feature_df = df.copy()

In [4]:
feature_df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [5]:
feature_df.shape

(9977, 13)

In [6]:
feature_df["Profit Margin (%)"] = (
    feature_df["Profit"] / feature_df["Sales"]
) * 100

In [7]:
feature_df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin (%)
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25

In [8]:
feature_df[
    ["Sales", "Profit", "Profit Margin (%)"]
].head(10)

      Sales    Profit  Profit Margin (%)
0  261.9600   41.9136              16.00
1  731.9400  219.5820              30.00
2   14.6200    6.8714              47.00
3  957.5775 -383.0310             -40.00
4   22.3680    2.5164              11.25
5   48.8600   14.1694              29.00
6    7.2800    1.9656              27.00
7  907.1520   90.7152              10.00
8   18.5040    5.7825              31.25
9  114.9000   34.4700              30.00

In [9]:
feature_df["Profit Margin (%)"] = (
    feature_df["Profit Margin (%)"]
    .round(2)
)

In [10]:
feature_df[
    ["Sales", "Profit", "Profit Margin (%)"]
].head(10)

      Sales    Profit  Profit Margin (%)
0  261.9600   41.9136              16.00
1  731.9400  219.5820              30.00
2   14.6200    6.8714              47.00
3  957.5775 -383.0310             -40.00
4   22.3680    2.5164              11.25
5   48.8600   14.1694              29.00
6    7.2800    1.9656              27.00
7  907.1520   90.7152              10.00
8   18.5040    5.7825              31.25
9  114.9000   34.4700              30.00

In [11]:
feature_df["Average Selling Price"] = (
    feature_df["Sales"] / feature_df["Quantity"]
)

In [12]:
feature_df["Average Selling Price"] = (
    feature_df["Average Selling Price"]
    .round(2)
)

In [13]:
feature_df[
    ["Sales", "Quantity", "Average Selling Price"]
].head(10)

      Sales  Quantity  Average Selling Price
0  261.9600         2                 130.98
1  731.9400         3                 243.98
2   14.6200         2                   7.31
3  957.5775         5                 191.52
4   22.3680         2                  11.18
5   48.8600         7                   6.98
6    7.2800         4                   1.82
7  907.1520         6                 151.19
8   18.5040         3                   6.17
9  114.9000         5                  22.98

In [14]:
feature_df["Average Selling Price"].describe()

count    9977.000000
mean       60.985341
std       143.029841
min         0.340000
25%         5.470000
50%        16.270000
75%        63.940000
max      3773.080000
Name: Average Selling Price, dtype: float64

In [15]:
feature_df["Discount Percentage"] = (
    feature_df["Discount"] * 100
)

In [16]:
feature_df["Discount Percentage"] = (
    feature_df["Discount Percentage"]
    .round(2)
)

In [17]:
feature_df[
    ["Discount", "Discount Percentage"]
].head(10)

   Discount  Discount Percentage
0      0.00                  0.0
1      0.00                  0.0
2      0.00                  0.0
3      0.45                 45.0
4      0.20                 20.0
5      0.00                  0.0
6      0.00                  0.0
7      0.20                 20.0
8      0.20                 20.0
9      0.00                  0.0

In [18]:
feature_df["Discount Percentage"].describe()

count    9977.000000
mean       15.627844
std        20.645520
min         0.000000
25%         0.000000
50%        20.000000
75%        20.000000
max        80.000000
Name: Discount Percentage, dtype: float64

In [19]:
feature_df[
    [
        "Profit Margin (%)",
        "Average Selling Price",
        "Discount Percentage"
    ]
].head(10)

   Profit Margin (%)  Average Selling Price  Discount Percentage
0              16.00                 130.98                  0.0
1              30.00                 243.98                  0.0
2              47.00                   7.31                  0.0
3             -40.00                 191.52                 45.0
4              11.25                  11.18                 20.0
5              29.00                   6.98                  0.0
6              27.00                   1.82                  0.0
7              10.00                 151.19                 20.0
8              31.25                   6.17                 20.0
9              30.00                  22.98                  0.0

In [20]:
feature_df[
    [
        "Profit Margin (%)",
        "Average Selling Price",
        "Discount Percentage"
    ]
].describe()

       Profit Margin (%)  Average Selling Price  Discount Percentage
count        9977.000000            9977.000000          9977.000000
mean           12.011351              60.985341            15.627844
std            46.663770             143.029841            20.645520
min          -275.000000               0.340000             0.000000
25%             7.500000               5.470000             0.000000
50%            27.000000              16.270000            20.000000
75%            36.250000              63.940000            20.000000
max            50.000000            3773.080000            80.000000

In [21]:
feature_df[
    [
        "Profit Margin (%)",
        "Average Selling Price",
        "Discount Percentage"
    ]
].isnull().sum()

Profit Margin (%)        0
Average Selling Price    0
Discount Percentage      0
dtype: int64

In [22]:
feature_df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin (%),Average Selling Price,Discount Percentage
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,130.98,0.0
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,243.98,0.0
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,7.31,0.0
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,191.52,45.0
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,11.18,20.0

In [23]:
feature_df.to_csv(
    "../data/cleaned/SampleSuperstore_Feature_Engineered.csv",
    index=False
)

In [24]:
final_df = pd.read_csv(
    "../data/cleaned/SampleSuperstore_Feature_Engineered.csv"
)

final_df.shape

(9977, 16)

In [25]:
print("Shape:", final_df.shape)
print("Missing Values:", final_df.isnull().sum().sum())
print("Duplicate Records:", final_df.duplicated().sum())

Shape: (9977, 16)
Missing Values: 0
Duplicate Records: 0